name: base-devel
on:
  push:
    paths:
      - ".github/workflows/base-devel.yaml"
      - "base-devel/*"
  schedule:
    - cron: "0 0 * * *"
env:
  REGISTRY: docker.pkg.github.com
  IMG: ${REGISTRY}/${GITHUB_REPOSITORY}/base-devel
  SHORTSHA: ${GITHUB_SHA:0:7}
jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master
      - name: login
        run: docker login ${REGISTRY} -u ${GITHUB_REPOSITORY%/*} -p $TOKEN
        env:
          TOKEN: ${{ secrets.PAT }}
      - name: build
        run: docker build -t $IMG:latest -t $IMG:$SHORTSHA base-devel
      - name: push sha
        run: docker push $IMG:$SHORTSHA
      - name: push latest
        run: docker push $IMG:latest
